### ISSUE TITLE
Agenda verbeteren met meerdere dagen support

### ISSUE THREAD

**Issue by GreenMan36** [svIndicium/site#19]
Dit ziet er niet uit;
![Image](https://github.com/svIndicium/site/assets/5887406/b62f9f8b-69eb-4a23-821f-2f730c26255c)

Iets als dit zou beter werken;
![Image](https://github.com/svIndicium/site/assets/5887406/a2cffeb5-64cd-4663-89e5-b4752089808f)

Misschien dat we hier later op terugkomen met een nieuw ontwerp maar dit is genoeg voor de functionaliteit, en niemand zal hier over klagen.

**Comment by GreenMan36** [comment]
Misscien kunnen we ook kijken of we de tijd kunnen weergeven als "Van 01:00 tot 01:00"

**Comment by siard-y** [comment]
```css

/* Element | https://svindicium.nl/ */

div.event:nth-child(1) > div:nth-child(1) > span:nth-child(3) {
  display: block;
}

/* index.css | https://svindicium.nl/assets/index.css */

.event .date[data-v-a838e2be] {
  /* max-height: 60px; */
  align-self: baseline;
}
```
